function output = import_cell_data(filename, dataLines, active_mass)
% IMPORTFILE Import data from a text file
%  ALXETMOS2C1CD7 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ALXETMOS2C1CD7 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  ALXETMoS2C1CD7 = importfile("C:\Users\Alexander\Documents\GitHub\PhD-Raw-Data\CoinCells\200109_ALV_ELECT_LM\200109_ALX_ETMoS2_C1_CD7.mpt", [104, 114]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Jan-2020 15:59:13

% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [104, Inf];
end

%Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "EcellV", "Var12", "Var13", "Var14", "Var15", "Var16", "halfcycle", "Var18", "QdischargemAh", "QchargemAh", "Var21", "Var22", "Var23", "Var24", "Var25"];
opts.SelectedVariableNames = ["EcellV", "halfcycle", "QdischargemAh", "QchargemAh"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "double", "string", "string", "string", "string", "string", "double", "string", "double", "double", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 18, 21, 22, 23, 24, 25], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 18, 21, 22, 23, 24, 25], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Convert the data
mydata = table2array(readtable(filename, opts));
voltage = mydata(:,1); 
halfcycle = mydata(:,2); %charging or discharging
discharge = mydata(:,3)/active_mass; % normalise the discharge capacity
charge = mydata(:,4)/active_mass; % normalise the charge capacity

% Output
output = [voltage,halfcycle,discharge,charge];

end